import XLSX from 'xlsx';
import mongoose from 'mongoose';
import Customer from '../model/customerModel.js';
import Product from '../model/productModel.js';
import Category from '../model/categoryModel.js';
import Purchase from '../model/purchaseModel.js';
import Quotation from '../model/quotationModel.js';
import Invoice from '../model/invoiceModel.js';
import Receipt from '../model/receiptModel.js';
import User from '../model/userModel.js';
import Role from '../model/roleModel.js';
import { isStrongPassword } from '../utils/passwordPolicy.js';

const models={customers:Customer,products:Product,categories:Category,purchases:Purchase,quotations:Quotation,invoices:Invoice,receipts:Receipt,users:User,roles:Role};
const permissionModule={customers:'customers',products:'products',categories:'products',purchases:'purchase',quotations:'quotations',invoices:'sales',receipts:'receipts',users:'users',roles:'users',vat:'vat'};
const allowed=(req,action)=>{ if(['users','roles'].includes(req.params.module)) return !!req.user?.isAdmin; return req.user?.isAdmin || !!req.user?.role?.permissions?.[permissionModule[req.params.module]]?.[action]; };
const jsonFields=new Set(['items','invoiceFiles','companyDocuments','permissions','allocations']);
const parseCell=(key,value)=>{if(typeof value!=='string')return value;const v=value.trim();if(!v)return undefined;if(jsonFields.has(key)||v.startsWith('{')||v.startsWith('[')){try{return JSON.parse(v)}catch{}}if(v==='true')return true;if(v==='false')return false;return value};
const clean=(obj)=>{const o={...obj};for(const k of ['_id','__v','createdAt','updatedAt','createdBy'])delete o[k];for(const k of Object.keys(o)){const v=parseCell(k,o[k]);if(v===undefined)delete o[k];else o[k]=v;}return o};
const exportRow=(doc)=>{const r={...doc};delete r.password;for(const k of Object.keys(r)){if(typeof r[k]==='object'&&r[k]!==null)r[k]=JSON.stringify(r[k]);}return r};
const exportVatWorkbook=async()=>{
  const [purchases,invoices]=await Promise.all([Purchase.find({}).lean(),Invoice.find({}).lean()]);
  const rows=[
    ...purchases.map(p=>({Type:'Purchase',RecordId:String(p._id),DocumentNo:p.purchaseNo,Date:p.dateOfPurchase,BaseAmount:p.subTotalCost,VatPercent:p.vatPercent,VatAmount:p.vatAmount,TotalAmount:p.totalCost,Status:p.status})),
    ...invoices.map(i=>({Type:'Invoice',RecordId:String(i._id),DocumentNo:i.invoiceNo,Date:i.invoiceDate,BaseAmount:i.subTotal,VatPercent:i.vatPercent,VatAmount:i.vatAmount,TotalAmount:i.totalAmount,Status:i.status}))
  ];
  const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'VAT Records');
  const info=XLSX.utils.aoa_to_sheet([['VAT IMPORT'],['To update VAT, keep Type, RecordId and VatPercent. The backend recalculates VAT and totals from the stored base amount.']]);
  XLSX.utils.book_append_sheet(wb,info,'Import Instructions');return wb;
};
const importVatRows=async(rows,session)=>{let created=0;for(let i=0;i<rows.length;i++){const row=rows[i];const type=String(row.Type||row.type||'').toLowerCase();const id=String(row.RecordId||row.recordId||row._id||'');const rate=Number(row.VatPercent??row.vatPercent);if(!id||!Number.isFinite(rate)||rate<0||rate>100)throw Object.assign(new Error(`Row ${i+2}: Type, RecordId and VatPercent between 0 and 100 are required`),{statusCode:400});if(type==='purchase'){const p=await Purchase.findById(id).session(session);if(!p)throw Object.assign(new Error(`Row ${i+2}: Purchase not found`),{statusCode:400});p.vatPercent=rate;p.vatAmount=Number(((p.subTotalCost||0)*rate/100).toFixed(2));p.totalCost=Number(((p.subTotalCost||0)+p.vatAmount).toFixed(2));await p.save({session});}else if(type==='invoice'){const inv=await Invoice.findById(id).session(session);if(!inv)throw Object.assign(new Error(`Row ${i+2}: Invoice not found`),{statusCode:400});if(inv.status!=='Active')throw Object.assign(new Error(`Row ${i+2}: Cancelled invoice VAT cannot be modified`),{statusCode:400});if(Number(inv.paidAmount||0)>0)throw Object.assign(new Error(`Row ${i+2}: Invoice VAT cannot be modified after a receipt has been applied`),{statusCode:400});const taxable=Math.max(0,Number(inv.subTotal||0)-Number(inv.discount||0));inv.vatPercent=rate;inv.vatAmount=Number((taxable*rate/100).toFixed(2));inv.totalAmount=Number((taxable+inv.vatAmount).toFixed(2));inv.balanceAmount=inv.totalAmount;await inv.save({session});}else throw Object.assign(new Error(`Row ${i+2}: Type must be Purchase or Invoice`),{statusCode:400});created++;}return{created,failed:0,errors:[]}};
export const exportModule=async(req,res,next)=>{try{if(!allowed(req,'view')&&!allowed(req,'report'))return res.status(403).json({success:false,message:'You do not have permission to export this module'});let wb;if(req.params.module==='vat'){wb=await exportVatWorkbook();}else{const Model=models[req.params.module];if(!Model)return res.status(400).json({success:false,message:'Unsupported module'});const docs=await Model.find({}).lean();const rows=docs.map(exportRow);const ws=XLSX.utils.json_to_sheet(rows);wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,req.params.module.slice(0,31));if(req.params.module==='users'){const info=XLSX.utils.aoa_to_sheet([['IMPORT NOTE'],['For new user imports, include a strong password column (10+ chars with uppercase, lowercase, number and special character). Existing passwords are never exported.']]);XLSX.utils.book_append_sheet(wb,info,'Import Instructions');}}const buf=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition',`attachment; filename="${req.params.module}-${new Date().toISOString().slice(0,10)}.xlsx"`);res.send(buf);}catch(e){next(e)}};
export const importModule=async(req,res,next)=>{let session;try{if(!allowed(req,'create')&&!allowed(req,'modify'))return res.status(403).json({success:false,message:'You do not have permission to import this module'});if(!req.file)return res.status(400).json({success:false,message:'Excel file is required'});const wb=XLSX.read(req.file.buffer,{type:'buffer'});const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});if(!rows.length)return res.status(400).json({success:false,message:'Excel sheet is empty'});if(rows.length>1000)return res.status(400).json({success:false,message:'Maximum 1000 rows per import'});session=await mongoose.startSession();session.startTransaction();let result;if(req.params.module==='vat'){result=await importVatRows(rows,session);}else{const Model=models[req.params.module];if(!Model){await session.abortTransaction();return res.status(400).json({success:false,message:'Unsupported module'});}let created=0;for(let i=0;i<rows.length;i++){try{const data=clean(rows[i]);data.createdBy=req.user._id;if(req.params.module==='users'){if(!isStrongPassword(data.password))throw new Error('strong password is required for user import');data.isAdmin=false;data.mustChangePassword=true;}if(req.params.module==='roles')data.isSystem=false;await Model.create([data],{session});created++;}catch(e){throw Object.assign(new Error(`Row ${i+2}: ${e.message}`),{statusCode:400});}}result={created,failed:0,errors:[]};}await session.commitTransaction();res.json({success:true,message:`Imported ${result.created} rows atomically`,data:result});}catch(e){if(session?.inTransaction())await session.abortTransaction().catch(()=>{});next(e);}finally{await session?.endSession().catch(()=>{});}};
